language: ruby
rvm:
  - 2.0.0
branches:
  only:
    - gh-pages
env:
    global:
        - secure: "zRWU9Q1kIOF/SMhnitH4t/lL+UFgxyMrz6NZGAVxxxDoBF3dPeG5Uv7U3AQOvjHZfkUT+tQM9rIvpOx0rQAkIDBCw71Xjlls7IJqq9ZZqqr9/lX/iWnhvkWpsg7YKptmS6JAAEIb7fcrf8F7NA8AoqZiR7GXw/w60iC+k8k13mD4XBvkhZu2XAu0w4yLmDOFaXvJuKtXE5cKoyTUeW6+/+lnyly7Bz0GyP6j9EB/FsxXdo9QMd7Db1EbADSftJOiERWJ/wFycjyFnZ1NMAvXR5jz35KV36y+xEdUe8JqLBEnmg7bfxBhhqFmlqHCIpIW/hVPC7Fc4qLCYIW8p6zB2IY3cCWQ/uE1WuGkfgbmteniqgZ85T5hAO6OEJlxa4f2eBwv1eWmHzQnj1Il2h6qEvUBcIkwvS+w337zQwQopvEIwXllFjupJ4pE4unS62kZg/94upZQRkdlIRRWC56/NIqjMTczPBspChLi94sGj8R8ZIKqDh59y6aAlEEEupvIwpJ89ME200ggZk7/3MaifFCO20hw+r3w7VfxXTggTf2FO/2VHFmxAzsRBr0ieS6qxVQnV3IQX66OuI+2LVuhDd/ay4/Dgy1fv6hXcGEJ8Tv0U6Rx//pKjKrrMeAqbv9UW9V3cFhtCbdSp85xEz4sEeKVZ2/uEihjb0wnnoga6As="
        - GH_OWNER=jwronline
        - GH_PROJECT_NAME=scripts
        - GH_EMAIL=hello@haroen.me
        - GH_USER=haroenv
        - GH_MESSAGE="compiled pdf [ci skip]"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install xfonts-75dpi
  - wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2/wkhtmltox-0.12.2_linux-trusty-amd64.deb
  - sudo dpkg -i wkhtmltox-0.12.2_linux-trusty-amd64.deb
install:
  - bundle install
script:
  - jekyll build
  - bash pdf.sh
after_success:
  - git config user.email "${GH_EMAIL}"
  - git config user.name "${GH_USER}"
  - git commit -am "${GH_MESSAGE}"
  # Any command that using GH_OAUTH_TOKEN must pipe the output to /dev/null to not expose your oauth token
  - git push https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} HEAD:gh-pages > /dev/null 2>&1
